export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_GOALS_START = 'FETCH_GOALS_START';
export const FETCH_GOALS_SUCCESS = 'FETCH_GOALS_SUCCESS';
export const FETCH_GOALS_FAIL = 'FETCH_GOALS_FAIL';
export const SAVE_GOAL_START = 'SAVE_GOAL_START';
export const SAVE_GOAL_SUCCESS = 'SAVE_GOAL_SUCCESS';
export const SAVE_GOAL_FAIL = 'SAVE_GOAL_FAIL';
